version: "3.8"

services:
  boosters:
    hostname: ubuntu
    # platform: linux/amd64 # win/mac win 주석o mac 주석x
    container_name: boostersUbuntu
    build:
      context: .
      dockerfile: ./ubuntu/Dockerfile
    privileged: true
    user: root
    stdin_open: true
    tty: true
    # cgroup_parent: m1 # win/mac win 주석o mac 주석x
    ports:
      - "80:80"
      - "443:443"
      - "3307:3306"
      - "5222:22"
      - "3000:3000"
      - "8080:8080"
      - "8100:8100"
      - "8200:8200"
      - "8300:8300"
    volumes:
      - ./apache2/sites-available/:/etc/apache2/sites-available/
      - ./apache2/sites-enabled/:/etc/apache2/sites-enabled/
      - ./apache2/apache2.conf:/etc/apache2/apache2.conf
      - ./apache2/ports.conf:/etc/apache2/ports.conf
      - ./php/7.2/apache2/php.ini:/etc/php/7.2/apache2/php.ini
      - ./php/7.2/cli/php.ini:/etc/php/7.2/cli/php.ini
      - ./mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    command: /sbin/init
